services:
  backend:
    image: oselejp/the-vault-keeper-backend:latest
    platform: linux/amd64
    ports:
      - "8000:8000"
    environment:
      - UPLOAD_DIR=/app/uploads
      - DATABASE_URL=sqlite:////app/data/vault-keeper.db
    volumes:
      - ./data/files:/app/uploads   # uploaded files persist here on the host
      - ./data:/app/data            # sqlite .db file persists here on the host

  frontend:
    image: oselejp/the-vault-keeper-frontend:latest
    platform: linux/amd64
    ports:
      - "5173:5173"
    depends_on:
      - backend
